### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by licaon-kter** [geopaparazzi/smash#182]
Rather easy to build:
```
Builds:
  - versionName: 1.7.4
    versionCode: 66
    commit: a84b2a505fa52fb9905976c8613bb0220bb41181
    sudo:
      - apt-get update || apt-get update
      - apt-get install -y openjdk-11-jdk-headless
      - update-alternatives --auto java
    output: build/app/outputs/apk/release/app-release-unsigned.apk
    srclibs:
      - flutter@stable
    rm:
      - .gradle
      - ios
      - linux
      - macos
    prebuild:
      - sed -i -e '/WORKAROUND/,+7d' android/app/build.gradle
      - echo "flutter.sdk=$$flutter$$" >> android/local.properties
    build:
      - $$flutter$$/bin/flutter config --no-analytics
      - $$flutter$$/bin/flutter packages pub get
      - $$flutter$$/bin/flutter build apk --no-tree-shake-icons
```
...buuut one of its deps brings `com/google/firebase` and `com/google/android/gms` which are not FOSS :(

Ref: https://www.virustotal.com/gui/file/ef887467737c54370f3b94abf2cf14bce7b600c61db07ba03e6614d23851d8b7/details see Activities and Strings

Ref: https://gitlab.com/fdroid/fdroiddata/-/issues/599
