### ISSUE TITLE
Compiling problems with Flutter v3.27.3

### ISSUE THREAD

**Issue by mbasa** [geopaparazzi/smash#291]
I was having problems compiling the newest Release 1.9.5 on my environment with the newest Flutter 3.27.3 version and had to do the following: 

* edit pubspec.yaml 

```
dependency_overrides:
  flutter_widget_from_html_core: ^0.15.2

dependencies:
....
  # MIT
  # flutter_slidable: ^3.0.1
  flutter_slidable: ^3.1.2

```

* edit android/gradle.properties and added

```
kotlin.jvm.target.validation.mode = IGNORE
```

After this, SMASH compiled cleanly and I was able to install and run it on my Samsung tablet without any problems.  The GTT is working correctly also. 

Just a fyi.
